// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivTCRTSPtilpMO0z5TqWRL17OfUiJ-vE',
    appId: '1:238591957435:web:aed819557edee66479cc9e',
    messagingSenderId: '238591957435',
    projectId: 'daily-planner-381f6',
    authDomain: 'daily-planner-381f6.firebaseapp.com',
    storageBucket: 'daily-planner-381f6.appspot.com',
    measurementId: 'G-K91T3DYV87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7OFkuxxIg7LBkSqc2bU9_WS2AjxjLvFc',
    appId: '1:238591957435:android:f1f6b919c4e811a279cc9e',
    messagingSenderId: '238591957435',
    projectId: 'daily-planner-381f6',
    storageBucket: 'daily-planner-381f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXV0nT6qdXdIFm0MMDLIcpCiWA4ZSlzI',
    appId: '1:238591957435:ios:1d91847548cbe0db79cc9e',
    messagingSenderId: '238591957435',
    projectId: 'daily-planner-381f6',
    storageBucket: 'daily-planner-381f6.appspot.com',
    iosBundleId: 'com.example.dailyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFXV0nT6qdXdIFm0MMDLIcpCiWA4ZSlzI',
    appId: '1:238591957435:ios:1d91847548cbe0db79cc9e',
    messagingSenderId: '238591957435',
    projectId: 'daily-planner-381f6',
    storageBucket: 'daily-planner-381f6.appspot.com',
    iosBundleId: 'com.example.dailyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDivTCRTSPtilpMO0z5TqWRL17OfUiJ-vE',
    appId: '1:238591957435:web:2cefecc67ffc42c279cc9e',
    messagingSenderId: '238591957435',
    projectId: 'daily-planner-381f6',
    authDomain: 'daily-planner-381f6.firebaseapp.com',
    storageBucket: 'daily-planner-381f6.appspot.com',
    measurementId: 'G-J24L8QS0PT',
  );

}